<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/1/12
 * Time: 13:27
 */

namespace api\controllers;


use yii\helpers\Html;
use yii\web\Controller;

class IndexController extends Controller
{

    public function init(){

    }
    public function beforeAction($action)
    {

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public function behaviors(){
        $behaviors = parent::behaviors();
        return $behaviors;
    }

    public function actionIndex(){
        echo json_encode(['aa'=>'bb']);
    }

}