<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/1/12
 * Time: 13:27
 */

namespace api\controllers;


use yii\helpers\Html;
use yii\web\Controller;

class IndexController extends Controller
{

    public function init(){
        echo 'init<br/>';
    }
    public function beforeAction($action)
    {

        echo 'before<br/>';
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    public function behaviors(){
        $behaviors = parent::behaviors();
        echo 'behavior<br/>';
        return $behaviors;
    }

    public function actionIndex(){

        $a = 'aaa';

        echo 'html';
    }

}